### ISSUE TITLE
Need error message on forms.

### ISSUE THREAD

**Issue by Stephen-SW** [Meeting-Maker/Front_End#34]
Need an error message on forms when onFormSubmit is called and there are errors within the form - (undesired inputs, required fields left empty)

**Comment by nehpethP** [comment]
attempt at error messages was done on CodeInput.js. attempt code is commented out

**Comment by Stephen-SW** [comment]
@BoKlassen proposed creating an error checking component for forms

**Comment by Stephen-SW** [comment]
The way that we are receiving dates on our forms does not match with javascript's date format.

**Comment by Stephen-SW** [comment]
(bug) The form for CreateMeetingDetails requires clicking 2 times on the submit button.

**Comment by Stephen-SW** [comment]
when you are joining a meeting as a guest the input field can be blank
